name: Debug build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/debug.yml'
  pull_request:
    branches:
      - main

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ github.token }}
  build:
    name: Local build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.1
      - name: Install Clang
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 15 clang lld
      - name: Build
        env:
          CC: clang-15
          CGO_LDFLAGS_ALLOW: -fuse-ld=lld
        run: |
          go run -v ./cmd/prebuild
          go run -v ./cmd/build-static
  cross:
    name: Cross Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: 386
            cc: clang-15 -target i386-pc-linux-gnu
            pkg: gcc-multilib
          - goos: linux
            goarch: arm64
            cc: clang-15 -target arm64-pc-linux-gnu --sysroot /usr/aarch64-linux-gnu
            pkg: libc-dev-arm64-cross
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.1
      - name: Install Clang
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 15 clang lld
      - name: Prebuild
        run: |
          sudo apt-get install -y ${{ matrix.pkg }}
          go build -v -o prebuild ./cmd/prebuild
          go build -v -o build ./cmd/build-static
      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CC: ${{ matrix.cc }}
          LD: lld-15
          CGO_LDFLAGS_ALLOW: -fuse-ld=lld
          CGO_ENABLED: 1
        run: |
          ./prebuild
          ./build